### ISSUE TITLE
Winforms Dark Mode: button background image not displayed

### ISSUE THREAD

**Issue by MarkusKuntner** [dotnet/winforms#13720]
**.NET version**
In .NET 9, button background images are displayed in dark mode.
In .NET 10 preview.6.25358.103, button background images are no longer displayed in dark mode.

**Steps to reproduce**
Create a winforms app, a form and a button with a background image. Activate the experimental dark mode
Activate the Windows 11 app dark mode
Compile with .NET9 (working) or .NET10(not working)

**Comment by Olina-Zhang** [comment]
@KlausLoeffelmann this is a known issue we found for your testing request, but didn't file a GH issue.

**Comment by KlausLoeffelmann** [comment]
Whoopsie daisies...
@Olina-Zhang, can you please file that one?

I get on to that immediately.

**Comment by Zheng-Li01** [comment]
**Following the steps:**
1. Create a winforms .NET Core project
2. Add a Button control with a background image
3. Enable DarkMode by Application.SetColorMode(SystemColorMode.Dark) in Program.cs file.
4. Build & run the application

**Results:**
For .NET 9.0, the button background images are displayed in dark mode.
<img width="418" height="446" alt="Image" src="https://github.com/user-attachments/assets/e25e8595-458c-4ba0-bfd7-a99ed1b77e63" />

For .NET 10.0, the button background images are no longer displayed in dark mode.
<img width="448" height="487" alt="Image" src="https://github.com/user-attachments/assets/be3e6fac-7280-4fa9-a600-4ed21d8f4901" />

**Comment by MarkusKuntner** [comment]
Maybe it is a different issue, but even in Windows High-Contrast Mode (for handicapped users) background images for buttons are not displayed. 
Tested for .NET8, .NET9 and .NET10

<img width="402" height="242" alt="Image" src="https://github.com/user-attachments/assets/7376912d-b3b8-4c59-b4cb-154632041b19" />
<img width="404" height="209" alt="Image" src="https://github.com/user-attachments/assets/a2ea501b-597d-4e2f-9530-7b12747e4083" />

**Comment by Zheng-Li01** [comment]
> Maybe it is a different issue, but even in Windows High-Contrast Mode (for handicapped users) background images for buttons are not displayed. Tested for .NET8, .NET9 and .NET10
> 
> <img alt="Image" width="402" height="242" src="https://private-user-images.githubusercontent.com/56679507/469325673-7376912d-b3b8-4c59-b4cb-154632041b19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMyMzMzNTUsIm5iZiI6MTc1MzIzMzA1NSwicGF0aCI6Ii81NjY3OTUwNy80NjkzMjU2NzMtNzM3NjkxMmQtYjNiOC00YzU5LWI0Y2ItMTU0NjMyMDQxYjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIzVDAxMTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MzIzOWJhOWM2OTI5NDkwMjQ3ZmYwOTU3MTRjMzRkMDVkYTAzZTRmYmM0MTMxMTUzYjM5ZDM2OGFiMmRlNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LBjDipH2V3BiKwD8AGxU8OWXZO4YRfqUX48LL8wkZx0"> <img alt="Image" width="404" height="209" src="https://private-user-images.githubusercontent.com/56679507/469325674-a2ea501b-597d-4e2f-9530-7b12747e4083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTMyMzMzNTUsIm5iZiI6MTc1MzIzMzA1NSwicGF0aCI6Ii81NjY3OTUwNy80NjkzMjU2NzQtYTJlYTUwMWItNTk3ZC00ZTJmLTk1MzAtN2IxMjc0N2U0MDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNzIzVDAxMTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZDY2ZGQ4M2RiOTZmYzYyNTNmMzE5ZDI3OGIyOGU3OGRlZjJkNzViZDU4ZjkyNzE0YjBhNzM0OTI4NDQ2NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.L9TYjwenyRmBY-3TpZ0Ae-aRb1PWDOMdtLF92oeEB0A">

Yes, also can reproduce this with all High Contrast Mode on both .NET Framework and .NET 8.0 ~ 10.0.

**Comment by MarkusKuntner** [comment]
In High-Contrast mode, this could originally have been a design decision to make the Button.Text easier to read. However, if Button.Text == String.Empty, the background image should be displayed in any case, because otherwise the button remains empty, especially when Button.Image is also not defined.

**Comment by KlausLoeffelmann** [comment]
> in any case, because otherwise the button remains empty, especially when Button.Image is also not defined.

True, but still the accepted approach for High Contrast/A11Y.
So, this behavior will likely remain for .NET and definitely remain for NetFx.

**Comment by KlausLoeffelmann** [comment]
Background Image Fix for Dark Mode will be RC1.

**Comment by Zheng-Li01** [comment]
The issue still can reproduce on .NET SDK 10.0.100-preview.7.25380.105 build, and based on the Klaus's comment, the issue will be fixed in the RC1, so reopen the issue to track until the fix bring in RC1.

**Comment by KlausLoeffelmann** [comment]
@Epica3055 and/or @leaf, do you want to give this a shot? 
If we would make RC1, we would need to have this though by tomorrow morning PCT, though.

_If that is too tight, by any means, I will reserve time for this tomorrow and then try to get it in in time. This is on very short notice, and I do not want you to get stressed out._

(We could also fix it for RC2, but I would rather have it in as early as possible.)

I think the fix is not too difficult.

It needs to be implemented in the context of the new button renderers, and in principle very similar to how we implemented the button image.

Thinks to keep in mind:
* Image and BackgroundImage can be combined, so we have a certain order of rendering (see below).
* We would need to keep `BackgroundImageLayout` with (`Tile`, `Center`, `Stretch`, `Zoom`, or `None`) into account.

From back to front then, the rendering order would be:

* Background color
* BackgroundImage (optional, layout-controlled)
* Border (where it applies)
* Image (optional, aligned relative to text)
* Text

Let's sync this evening (your morning), if we can make this work!

Thanks!
@merriemcgaw FYI.

**Comment by Amy-Li03** [comment]
Verified this issue in .NET 10.0 RC1 SDK test pass build: 10.0.100-rc.1.25416.112, it was fixed when button's FlatStyle is Flat & Popup.
For FlatStyle= Standard, the button background image is still not displayed in dark mode, have filed a new GH issue: [13823 ](https://github.com/dotnet/winforms/issues/13823) to track.
<img width="637" height="388" alt="Image" src="https://github.com/user-attachments/assets/040e9e3d-2a18-4b26-98e5-9c4a575821ce" />
