### ISSUE TITLE
Text is longer than 43679 and its contents cannot be displayed in DataGridView

### ISSUE THREAD

**Issue by scalablecory** [dotnet/winforms#1995]
_From @15092368540 on Friday, August 23, 2019 10:38:07 PM_

with NET Core 3.0.0-preview8, the point is that can't show, not long enough.
![88759-abug](https://user-images.githubusercontent.com/49462433/63627269-7d5a0d80-c639-11e9-82b6-9997a8c186f0.png)

_Copied from original issue: dotnet/core#3242_

**Comment by scalablecory** [comment]
_From @15092368540 on Monday, August 26, 2019 11:59:01 AM_

Temporarily found a way to fix from developercommunity.visualstudio.com
Codes:
private void DataGridView1_CellFormatting(object sender, DataGridViewCellFormattingEventArgs e)
{
	string str = e.Value.ToString();
	if (str.Length >= 43679)
	{
		e.Value = str.Substring(0, 43679);
		e.FormattingApplied = true;
	}
}

**Comment by scalablecory** [comment]
_From @15092368540 on Tuesday, August 27, 2019 7:06:30 PM_

by Tested, the above method does not achieve the desired purpose when there are two columns or more

**Comment by merriemcgaw** [comment]
Have you encountered this issue before on .NET Framework?

**Comment by RussKie** [comment]
@15092368540 could you please provide more information in order for use to better triage your request.

* Have you encountered this issue before on .NET Framework?
* Have you tried the final release of .NET Core 3.0?

We will also need a simple sample app that reproduces the error.

Thanks

**Comment by 15092368540** [comment]
[datagridviewtest.zip](https://github.com/dotnet/winforms/files/3684042/datagridviewtest.zip)
![test](https://user-images.githubusercontent.com/49462433/66091805-cea3d800-e5bb-11e9-9f46-760fe792023b.png)

**Comment by RussKie** [comment]
Thank you.

Have you encountered this issue before on .NET Framework?

**Comment by 15092368540** [comment]
datagridviewtest.zip is a file of test project

**Comment by RussKie** [comment]
I see that your example is targeting .NET 4.7.2. This repo is only for .NET Core version of Windows Forms.
If you provide a repro for .NET Core app exhibiting the issue - it will be certainly looked at. 

You welcome to submit your issue with .NET Frameworj via VS Feedback:
![image](https://user-images.githubusercontent.com/4403806/66092102-f00dbf80-e5cd-11e9-9989-9472c22f3426.png)
However you have significantly higher chances of the issue fixed in .NET Core (if it reproduces) than .NET Framework.

**Comment by weltkante** [comment]
@RussKie seriously? I find VS Feedback mostly redirects issues against UI frameworks to the Core repositories. I think an issue will only be fixed in Desktop if its a security issue. Even then they want it also fixed in the Core repository so they'll still recreate the issue here.

Also it is trivial to verify that the bug still exists in Core and has not been fixed, I just dragged the Form1 into a blank Core WinForms project and it exhibits the same behavior. Theres no reason why this sample is not sufficient to be looked at in the Core repo.

That said, considering its not a regression I'm not sure if displaying that long of a text falls into the valid use case of the DataGridView, so if you want to reject the issue there are better reasons than "the sample was created with the wrong target framework" ...

Other similar "upscaled" use cases have already been rejected (e.g. when creating a huge number of columns) and I agree that its not the place of WinForms to work around limitations of the win32 API, it just doesn't fall into the use case of the provided controls and the programmer should design for it if he needs these scenarios working anyways (perhaps by truncating the text and displaying it in a separate window when clicked, these texts certainly will never be visible in a grid cell all at once anyways)

**Comment by RussKie** [comment]
> I find VS Feedback mostly redirects issues against UI frameworks to the Core repositories, but even if they intend to fix it in Desktop they also want it fixed in the Core repository so they'll still recreate the issue here. 

The issues is reported as .NET 4.7.2 issue. Until we have a confirmation the same is failing in .NET Core we can't accept it.

@15092368540 you are welcome to submit a .NET Core repro and we'll reopen the ticket. 
You are also welcome to submit a PR with a fix.

**Comment by weltkante** [comment]
> Also it is trivial to verify that the bug still exists in Core and has not been fixed, **I just dragged the Form1 into a blank Core WinForms project and it exhibits the same behavior**. Theres no reason why this sample is not sufficient to be looked at in the Core repo.
