### ISSUE TITLE
RichTextBox paint result is not good

### ISSUE THREAD

**Issue by TempeBrennan** [dotnet/winforms#2989]
* .NET Core Version: 

3.1.200

* Have you experienced this same bug with .NET Framework?: 

Yes

**Problem description:**

Use sendMessage API to get RichTextBox paint result and draw to a panel:

https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessage

```
UnsafeNativeMethods.SendMessage(new HandleRef(this.myRichTextBox1, this.myRichTextBox1.Handle), UnsafeNativeMethods.EM_FORMATRANGE, new IntPtr(1), ref fmt);
UnsafeNativeMethods.SendMessage(new HandleRef(this.myRichTextBox1, this.myRichTextBox1.Handle), UnsafeNativeMethods.EM_FORMATRANGE, IntPtr.Zero, IntPtr.Zero);
```

set font, everything is ok :
![image](https://user-images.githubusercontent.com/51563666/77041169-5b204680-69f4-11ea-953d-3a39cac99869.png)

set selection font, paint result is not good:
![image](https://user-images.githubusercontent.com/51563666/77041366-be11dd80-69f4-11ea-8f16-523cc92373dd.png)

paint method code:
```
        public Form1()
        {
            InitializeComponent();
            this.myRichTextBox1.SelectionStart = 0;
            this.myRichTextBox1.SelectionLength = 5;
            this.myRichTextBox1.SelectionFont = new Font("MS PGothic", (float)11.25);
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {
            var render = new MyRichTextBox();
            render.Rtf = this.myRichTextBox1.Rtf;

            using (Metafile buffer = new Metafile(render.Graphics.GetHdc(), new RectangleF(0f, 0f, (float)render.Bounds.Width, (float)render.Bounds.Height),
                           MetafileFrameUnit.Pixel, EmfType.EmfPlusDual))
            {
                render.Graphics.ReleaseHdc();
                using (Graphics bufferGraphics = Graphics.FromImage(buffer))
                {
                    var hdc = bufferGraphics.GetHdc();
                    try
                    {
                        FORMATRANGE fmt = new FORMATRANGE();
                        fmt.hdc = hdc;
                        fmt.hdcTarget = hdc;
                        fmt.rc = new RECT(0, 0, 1500, 1500);
                        fmt.rcPage = new RECT(0, 0, 1500, 1500);
                        fmt.chrg.cpMin = 0;
                        fmt.chrg.cpMax = -1;
                        UnsafeNativeMethods.SendMessage(new HandleRef(this.myRichTextBox1, this.myRichTextBox1.Handle), UnsafeNativeMethods.EM_FORMATRANGE, new IntPtr(1), ref fmt);
                        UnsafeNativeMethods.SendMessage(new HandleRef(this.myRichTextBox1, this.myRichTextBox1.Handle), UnsafeNativeMethods.EM_FORMATRANGE, IntPtr.Zero, IntPtr.Zero);
                    }
                    finally
                    {
                        bufferGraphics.ReleaseHdc(hdc);
                    }
                }
                e.Graphics.DrawImage(buffer, render.Bounds, 0f, 0f, (float)render.Bounds.Width, (float)render.Bounds.Height, GraphicsUnit.Pixel);
            }
        }
```

More detail please reference TestRichTextBoxNETCoreWithAPI

If change to use DrawToBitmap method:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.drawtobitmap?view=netframework-4.8

selection font is ok:
![image](https://user-images.githubusercontent.com/51563666/77041689-514b1300-69f5-11ea-8a85-24faf0e26e0b.png)

font is not good if set rich textbox transparent:
![image](https://user-images.githubusercontent.com/51563666/77041509-ffa28880-69f4-11ea-9699-04f3f8ef7e56.png)

To solve this issue, we have to give up transparent back color, then issue is fixed:
![image](https://user-images.githubusercontent.com/51563666/77041809-89525600-69f5-11ea-94b3-a9060b0e21bf.png)

paint method code:

```
        public Form1()
        {
            InitializeComponent();
            this.richTextBox1.Text = "あいうえお";
            this.richTextBox1.SelectionStart = 0;
            this.richTextBox1.SelectionLength = 5;
            this.richTextBox1.SelectionFont = new Font("MS PGothic", (float)11.25);

            this.richTextBox2.Text = "あいうえお";
            this.richTextBox2.SelectionStart = 0;
            this.richTextBox2.SelectionLength = 5;
            this.richTextBox2.SelectionFont = new Font("MS PGothic", (float)11.25);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            this.panel1.Invalidate();
        }

        private void panel1_Paint(object sender, PaintEventArgs e)
        {
            var img = new Bitmap(this.richTextBox1.Width, this.richTextBox1.Height);
            this.richTextBox1.DrawToBitmap(img, new Rectangle(0, 0, this.richTextBox1.Width, this.richTextBox1.Height));
            e.Graphics.DrawImage(img, 0, 0);
        }

        private void panel2_Paint(object sender, PaintEventArgs e)
        {
            var img = new Bitmap(this.richTextBox2.Width, this.richTextBox2.Height);
            this.richTextBox2.DrawToBitmap(img, new Rectangle(0, 0, this.richTextBox2.Width, this.richTextBox2.Height));
            e.Graphics.DrawImage(img, 0, 0);
        }

        private void button2_Click(object sender, EventArgs e)
        {
            this.panel2.Invalidate();
        }
```

**Expected behavior:**
Choose any API to get correct result to paint a rich textbox like real control.
Or maybe this is limitation and is there any workaround to solve it? 
Thanks a lot!

**Minimal repro:**
[TestRichTextBox.zip](https://github.com/dotnet/winforms/files/4353148/TestRichTextBox.zip)

**Comment by RussKie** [comment]
Do you think you could check it in .NET5 Preview1, that we've just released? We've optimised the interops quite a bit.

...and you're welcome to send a PR with fix 😉

**Comment by weltkante** [comment]
As far as transparency is concerned, GDI never supported transparency so it just looks at the color bytes of your transparent pixels (which are zero, i.e. black), so when drawing on transparent pixels with GDI what you end up with is alpha blending on a black background, which ends up with what you've shown. When rendering native controls implemented with GDI you always need to render them against a background, not against transparent pixels.

Regard the font quality issue I don't have any immediate idea what is going wrong.

**Comment by merriemcgaw** [comment]
This doesn't look like something WinForms is able to do much in this case.

**Comment by TempeBrennan** [comment]
@RussKie Thanks, I update .NET 5.0 and still have this issue.

@weltkante Thanks your replay.   Now I can understand this is a limitation. GDI doesn't support transprant back color.
So I give up transparent but still find issue.

So I create a new test project
![image](https://user-images.githubusercontent.com/51563666/77133307-9aef3880-6a9d-11ea-9171-162681c45e8b.png)

One use win32 API and another use DrawBitmap method

1. First input "あ", then click paint button. result is good.
![image](https://user-images.githubusercontent.com/51563666/77133433-06d1a100-6a9e-11ea-8918-624f9ca54573.png)

2. Second open world pad and input "あ"
![image](https://user-images.githubusercontent.com/51563666/77133473-25379c80-6a9e-11ea-982c-f3ca91e25eeb.png)

3. copy paste to rich textbox then click paint button again. Only DrawBitmap paint is good. another is bad.
![image](https://user-images.githubusercontent.com/51563666/77133548-6039d000-6a9e-11ea-84d8-9b6cd2b6e944.png)

Maybe this issue is not easy to investigate. I still try to find better solution. 
But still looking forward any idea. Thanks!

My Test project:
[TestRichTextBoxPaint.zip](https://github.com/dotnet/winforms/files/4357848/TestRichTextBoxPaint.zip)

**Comment by weltkante** [comment]
Took a quick look, I suspect the difference comes from the fact that you use a metafile and render via `e.Graphics` which is probably using GDI+ not classic GDI, thus rendering looks different. I'll take a deeper look into it over the weekend, it may be that you need to use Win32 GDI calls to render the metafile, not just to record it, or it may be an inherent limitation of metafiles. I'll get back to you once I know more.

Alltogether I agree with the resolution of closing the issue, as this has nothing to do with WinForms or .NET - you are just seeing different results when using different native APIs. (Note that `DrawToBitmap` also uses a SendMessage native call, but with a different command.)

**Comment by weltkante** [comment]
When you paste from browser to RichTextBox you get font `Yu Gothic` , when you paste into WordPad you get font `MS PGothic`. See below for RTF snippets you can paste into the constructor of your test.

This explains the difference you get depending on how you copy/paste - its simply different fonts and `MS PGothic` doesn't play well with your metafile rendering technique (the low-size aliased glyphs get replaced by vector glyphs).

I'll continue looking into the details over the weekend, I happen to be looking into win32 font rendering recently and your test cases seem interesting enough to pick apart :-)

```csharp
// copy/paste result from browser to RichTextBox
richTextBox1.Rtf = @"{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031
{\fonttbl{\f0\fnil\fcharset128 Yu Gothic;}{\f1\fnil\fcharset0 Calibri;}
{\f2\fnil\fcharset0 Microsoft Sans Serif;}}\viewkind4\uc1 \pard\sa200\sl276\slmult1\f0\fs8\lang7
\'82\'a0\fs10\'82\'a0\fs12\'82\'a0\fs14\'82\'a0\fs16\'82\'a0\fs18\'82\'a0\fs20\'82\'a0\fs22\'82
\'a0\fs24\'82\'a0\fs28\'82\'a0\fs32\'82\'a0\fs36\'82\'a0\fs40\'82\'a0\fs44\'82\'a0\fs48\'82\'a0
\fs52\'82\'a0\f1\fs22\par\pard\f2\fs17\lang1031\par}";
```
```csharp
// copy/paste result from browser to WordPad
richTextBox1.Rtf = @"{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1031
{\fonttbl{\f0\fnil\fcharset128 MS PGothic;}{\f1\fnil\fcharset0 Calibri;}
{\f2\fnil\fcharset0 Microsoft Sans Serif;}}\viewkind4\uc1 \pard\sa200\sl276\slmult1\f0\fs8\lang7
\'82\'a0\fs10\'82\'a0\fs12\'82\'a0\fs14\'82\'a0\fs16\'82\'a0\fs18\'82\'a0\fs20\'82\'a0\fs22\'82
\'a0\fs24\'82\'a0\fs28\'82\'a0\fs32\'82\'a0\fs36\'82\'a0\fs40\'82\'a0\fs44\'82\'a0\fs48\'82\'a0
\fs52\'82\'a0\f1\fs22\par\pard\f2\fs17\lang1031\par}";
```

**Comment by weltkante** [comment]
The problems with `MS PGothic` font don't come from the RichTextBox, they are caused by your metafile rendering code. If you use `SendMessage(EM_FORMATRANGE)` to render into a bitmap instead of a metafile everything works fine. This font relies on hinting to get the sharp pixel lines at low resolutions, using a metafile the way you are doing messes the resolution information up, so when drawing the metafile back to screen it gets confused about what resolution is correct and choses cleartype vector rendering instead of antialiased hinting.

I found several workarounds, the easiest is calling [`SetGraphicsMode(hdc, 2)`](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-setgraphicsmode) just before the `SendMessage(EM_FORMATRANGE)` call. The number 2 is `GM_ADVANCED`, while the default is 1, `GM_COMPATIBLE`. The reason why this helps is because the metafile records a "world transform" to relate the mismatching rendering resolutions and enabling advanced graphics mode allows text rendering to respect that recorded information and figure out what the original resolution was. I think you could theoretically get it to work in the default graphics mode but this needs very careful setup of the DC/Metafile coordinate system to prevent any mismatch.

The other two alternatives to fix the font rendering involve [EnumEnhMetaFile](https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-enumenhmetafile) and either fixing the wrong resolution information in the metafile (so it doesn't need a world transform and can render in default graphics mode), or alternatively configuring fonts to be loaded with classic AntiAlias hinting instead of ClearType rendering. However processing the metafile after recording seems a bit overkill, it is a lot of work to define the necessary interop to use it from C#, so `SetGraphicsMode` seems to be the better choice for you if it doesn't cause other negative effects. (The docs mention that rectangles can be off by one pixel on the right/bottom, and arcs being calculated differently, but I don't think that would affect RichTextBox rendering too much. Rectangles might used when you have a background color for a text span, but one pixel off shouldn't be much of an issue.)

**Comment by TempeBrennan** [comment]
@weltkante Thanks for your kind help.

> I found several workarounds, the easiest is calling SetGraphicsMode(hdc, 2) just before the SendMessage(EM_FORMATRANGE) call. The number 2 is GM_ADVANCED, while the default is 1, GM_COMPATIBLE

I tried to add ths code to my test project
```
UnsafeNativeMethods.SetGraphicsMode(hdc, 2);
```
I can see MS PGothic font paint well now. So impressed!
We choose `Metafile` this type is to support vector image.

I need to check API carefully before report this issue.
Now I am learning why this method can solve this issue. Thanks again.

**Comment by TempeBrennan** [comment]
@weltkante 
I found after add your workaround to keep use sendMessage to paint.
Although change richtextbox backcolor to transparent, paint effect still good.

Thanks again. I am also want to learn more details. Actually, I never know hinted glyphs and vector glyphs. I need to make up missed lessions.

**Comment by RussKie** [comment]
Thank you @weltkante 🥇
