### ISSUE TITLE
ApplicationConfiguration Code Generation bug

### ISSUE THREAD

**Issue by deng0** [dotnet/winforms#6144]
* .NET Core Version: 
6.0.0

**Problem description:**
When windows system language is set to a language which uses comma as decimal separator the code generator which creates the ApplicationConfiguration class messes up the decimal separator in emSize for the font

For instance when `<ApplicationDefaultFont>Microsoft Sans Serif, 8.25pt</ApplicationDefaultFont>` is set int the csproj file, the following is generated, which obviously does not compile:
`Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8,25f, (FontStyle)0, (GraphicsUnit)3));`

The bug is probably here:
https://github.com/dotnet/winforms/blob/c87540e90d424d126306a7f1909f75672ca6004f/src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontDescriptor.cs#L35

It obviously should use invariant culture to create that string.

**Comment by RussKie** [comment]
The font descriptor must be culture agnostic. This is by design. We'll make sure to note this in the docs (these are coming shortly).

/cc: @adegeo FYI

**Comment by RussKie** [comment]
@deng0 can you please provide more context - what is your Windows default locale, what is the application locale, etc.? Thank you

**Comment by deng0** [comment]
@RussKie 
I see that you already committed a change that should fix this bug.
But anyway regarding your question:
The problem can be reproduced by setting the decimal symbol to comma in Control Panel - Region - Additional Settings:
![image](https://user-images.githubusercontent.com/4224837/141249489-002a3894-bc57-4b76-8c05-8760e79568e1.png)

Using `Size.ToString(CultureInfo.InvariantCulture)` is probably the easiest fix, but I'm wondering if it would be better to have these kind (or perhaps even all) code generators/analyzers generally run with the InvariantCulture as CultureInfo.CurrentCulture to prevent these kinds of bugs?

**Comment by RussKie** [comment]
> The problem can be reproduced by setting the decimal symbol to comma in Control Panel - Region - Additional Settings:

Yes, thank you. I just wanted to make sure I tested your specific scenario.

> if it would be better to have these kind (or perhaps even all) code generators/analyzers generally run with the InvariantCulture as CultureInfo.CurrentCulture to prevent these kinds of bugs?

`CultureInfo.CurrentCulture` doesn't work well for regionally distributed teams, and would cause more friction than requiring common settings to be set the invariant culture.

**Comment by deng0** [comment]
@RussKie  Thanks for the quick reply.

> `CultureInfo.CurrentCulture` doesn't work well for regionally distributed teams, and would cause more friction than requiring common settings to be set the invariant culture.

I think you misunderstood. I was suggesting overriding CultureInfo.CurrentCulture with CultureInfo.InvariantCulture for Code Generators/Analyzers, to make sure that the same code is generated regardless of system culture.

**Comment by Amy-Li03** [comment]
@RussKie verified this issue on .NET 6.0.101 service build, issue is still reproducing, whether this PR doesn't merge into this build?
![image](https://user-images.githubusercontent.com/62929087/143397416-2ead255a-6965-4425-b80b-dbdaf3e1ea14.png)
We also verified this issue on .NET 7.0 latest build: 7.0.100-alpha.1.21568.2, issue was fixed.

**Comment by RussKie** [comment]
Unfortunately the fix hasn't made its way into 6.0.1, and will be shipped in 6.0.2 servicing release.

**Comment by RussKie** [comment]
The fix went out in 6.0.2.
