### ISSUE TITLE
Setting a font form disables autoscaling

### ISSUE THREAD

**Issue by dhrdlicka** [dotnet/winforms#6151]
* .NET Core Version: 
6.0.0

* Have you experienced this same bug with .NET Framework?: 
No

**Problem description:**

Forms with an explicitly set font do not automatically scale on font/DPI size changes. The `AutoScaleDimensions` property is reset from whatever value the app was built with, to the current host settings when `Font` gets set. This leads to the form never getting adjusted when the design time font/DPI size does not match the runtime one.

This does not happen in .NET 5.0.

**Expected behavior:**

Forms should show at proper scale when a custom font is set.

**Minimal repro:**

* Create a form, change the font and set `AutoScaleMode` to Font or DPI.
* Change the system DPI.
* The form and control sizes stay the same no matter the system settings.
![AutoScaleDimensionsRepro_ZWf4kWAEL3](https://user-images.githubusercontent.com/13226155/141035686-cc067956-dc47-47e6-91d5-c622030d7cb1.png)
![AutoScaleDimensionsRepro_MBSFXFgrqN](https://user-images.githubusercontent.com/13226155/141035708-295c3018-cef4-4cfa-aa39-7aa1d3a1a21a.png)

**Comment by RussKie** [comment]
Please provide a simple project that reproduces the issue.

**Comment by dreddy-work** [comment]
@dhrdlicka , its little unclear on how you are setting Font here. it would help to share  your test app here and also a possible giff with how you are changing system settings in this case.

**Comment by dhrdlicka** [comment]
Here is a repro project: [AutoScaleDimensionsRepro.zip](https://github.com/dotnet/winforms/files/7516303/AutoScaleDimensionsRepro.zip)

I am changing DPI settings in the Settings app, though I also noticed that the bug can be reproduced by directly changing the `AutoScaleDimensions` in the designer code.

**Comment by kpreisser** [comment]
Hi, we also run into this issue after upgrading our app from .NET 5.0.12 to .NET 6.0.0: Forms are no longer scaled with high DPI modes when we set the `Font` property.

I can reproduce this also with the following minimal program (using 100% DPI mode) by setting different `AutoScaleDimensions` (as noted by @dhrdlicka):
```cs
static class Program
{
    [STAThread]
    static void Main()
    {
        Application.EnableVisualStyles();
        Application.SetCompatibleTextRenderingDefault(false);
        Application.SetHighDpiMode(HighDpiMode.DpiUnaware);

        var f = new Form();
        f.SuspendLayout();

        f.Size = new Size(100, 80);
        f.AutoScaleDimensions = new SizeF(48, 48);
        f.AutoScaleMode = AutoScaleMode.Dpi;
        f.Font = new Font("Segoe UI", 9f);

        var b = new Button() {
            Size = new Size(40, 11),
            Text = "Hello World"
        };
        f.Controls.Add(b);

        f.ResumeLayout(false);
        f.PerformLayout();

        Debug.WriteLine("Button.Width: Expected=80, Actual=" + b.Width);
        Application.Run(f);
    }    
}
```

Running with .NET 5.0.12 prints `Button.Width: Expected=80, Actual=80`, and the form is scaled:
![grafik](https://user-images.githubusercontent.com/13289184/141280001-fadfe6c7-09f6-4fc2-af5d-524b5c5eb505.png)

However, when running with .NET 6.0.0, it prints `Button.Width: Expected=80, Actual=40`, and the form is not scaled:
![grafik](https://user-images.githubusercontent.com/13289184/141280099-1e08b139-9e1d-47a6-b0c5-0cae7d76a690.png)

When changing the code so that `f.Font` is set before `f.AutoScaleMode`, the issue goes away. However, I think the designer sets properties alphabetically, so `this.AutoScaleMode` is set before `this.Font`.

Thank you!

**Comment by dreddy-work** [comment]
Thank you  @dhrdlicka  and @kpreisser . I will look into it and get it addressed in coming servicing release.

**Comment by dreddy-work** [comment]
@dhrdlicka and @kpreisser ,  draft PR is up and linked here. Would you help check your applications targeting 6.0 working fine with this change?

**Comment by kpreisser** [comment]
Hi @dreddy-work,
thanks for providing the PR.
Unfortunatly, when testing the above minimal program with `System.Windows.Forms.dll` built from the PR (commit 628ebc015b8663b68039bdb6bd72fdfda71ca2d8), I can still reproduce the issue that the form is not scaled when `f.Font` is set after `f.AutoScaleMode`, but it is scaled when switching the two lines. Additionally, I can reproduce it with our application when running on a monitor with 150% DPI.

When debugging, I can see that when the code is in this order:
```cs
f.AutoScaleMode = AutoScaleMode.Dpi;
f.Font = new Font("Segoe UI", 9f);
```
then `ContainerControl.PerformAutoScale()` is called two times:
- 1st (from `ContainerControl.OnFontChanged`): `AutoScaleFactor` is `2`, `includedBounds` is `false`, `causedByFontChanged` is `true`
- 2nd (from `ContainerControl.OnLayoutResuming`): `AutoScaleFactor` is `1`, `includedBounds` is `true`, `causedByFontChanged` is `false`

and the form is not scaled.

When changing these to 
```cs
f.Font = new Font("Segoe UI", 9f);
f.AutoScaleMode = AutoScaleMode.Dpi;
```
then `ContainerControl.PerformAutoScale()` is called two times:
- 1st (from `ContainerControl.OnFontChanged`): `AutoScaleFactor` is `1`, `includedBounds` is `false`, `causedByFontChanged` is `true`
- 2nd (from `ContainerControl.OnLayoutResuming`): `AutoScaleFactor` is `2`, `includedBounds` is `true`, `causedByFontChanged` is `false`

and the form is scaled.


However, I have not looked into why in the first scenario the controls are not scaled even though `AutoScaleFactor` is `2` (it seems to be caused by `includedBounds` being `false`).
Thank you!

**Comment by kirsan31** [comment]
@kpreisser this is different issue (your bug is from the days of .net framework - no regression). See https://github.com/dotnet/winforms/issues/3202.
And original issue is regression (according to the author) even from .net5. But I don't really know how his code could work in .NET Framework and .Net5 due to not fixed #3202 :man_shrugging:

**Comment by kpreisser** [comment]
Hi @kirsan31,

when I run the code from https://github.com/dotnet/winforms/issues/6151#issuecomment-966177823 with .NET Core 3.1.21 and .NET 5.0.12, the form is correctly scaled. Only when running it with .NET 6.0.0, it is not scaled. So it seems to be a regression from .NET 5.0 as noted in the OP; I don't think it's a different issue.

However, the symptoms (scaling works again when `Font` is set before `AutoScaleMode`) look exactly like #3202, so I'm not sure why that issue occured even with .NET Core 3.1 in your case.

I also tested the repro project **AutoScaleDimensionsRepro.zip** from https://github.com/dotnet/winforms/issues/6151#issuecomment-965803190, and the issue (controls are not scaled) still reproduced for me with `System.Windows.Forms.dll` built from the PR. However, as soon as I move the line where `this.Font` is set (in `InitializeComponent()` in `Form1.Designer.cs`) before `this.AutoScaleSize` is set, the form is scaled correctly (in this case to a smaller size).

**Comment by kirsan31** [comment]
Ok, I figured out what's going on.

0. The root of all problems are : *DPI scaling is broken if font of the form set after DPI scaling logic code*. See [#3202](https://github.com/dotnet/winforms/issues/3202) for details.
1. The necessary conditions for [#3202](https://github.com/dotnet/winforms/issues/3202) (all framework versions) are:
   1. `AutoScaleMode.Font`.
   2. Font of the form must be different from current system font.
2. And the regression in .Net6 is that now we no need any addition conditions above. So, in .Net6 for broke DPI scaling you simple need to **set any Font after any DPI scaling logic**.

**Comment by kpreisser** [comment]
Hi @kirsan31,
thank you. That matches with what I figured after debugging .NET 5.0:
In NET 5.0, the `Control.Font` setter had the following condition which checks `!resolved.Equals(value)`:
https://github.com/dotnet/winforms/blob/6120af5607760b0daa3530a8cf8f8777c6992631/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L2127-L2147

So, when setting the font as `new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point)`, it equals the old font, and the `OnFontChanged` method is not called. In .NET 6.0, this condition was removed with #5032, and so `ContainerControl.PerformAutoScale()` is called from the `Font` setter which seems to cause the issue.

When I change the set font in `Form1.Designer.cs` to a font e.g. with `FontStyle.Bold`, then the issue also reproduces with .NET 5.0. So it seems the root cause is still #3202, but previously it did not occur when setting a Font that equals the default font.

**Comment by dreddy-work** [comment]
Thanks Guys. For now, I delinked the other bug that duped to this and get fixes out separately.

**Comment by dreddy-work** [comment]
@Olina-Zhang , given there were multiple fixes went in over the time, can you help verify this in latest build?

**Comment by Philip-Wang01** [comment]
@dreddy-work , verified this issue with latest 7.0 build : 7.0.100-preview.6.22314.18 and 6.0 build: 6.0.400-preview.22301.10. This issue reproduces in 6.0, but not in 7.0.
300% main screen: 
![image](https://user-images.githubusercontent.com/86937911/173767803-c7a0a573-f1d8-4f13-94f1-e4de9d1587db.png)
![image](https://user-images.githubusercontent.com/86937911/173767897-cb39d65c-1867-4664-b0bc-583b9622183c.png)

**Comment by dreddy-work** [comment]
Closing with confirmation form 7.0
