### ISSUE TITLE
The ToolStripButton borders have low color contrast ratio in high contrast mode on win11 OS

### ISSUE THREAD

**Issue by Amy-Li03** [dotnet/winforms#6322]
* OS Version: Win11
* .NET Core Version: 
.NET Core SDK: 7.0.0-alpha.1.21568.2

* Have you experienced this same bug with .NET Framework?: 
Yes

* More info: 
1. There is a known issue: [6220](https://github.com/dotnet/winforms/issues/6220) about this on Win10 OS
2. This issue is reproducing when high contrast is Aquatic/Dusk/Night sky
3. This issue doesn't repro when high contrast is Desert

**Minimal repro:**
1. Create a Winforms application with ToolStrip added
2. Set ToolStrip.RenderMode as **System**
3. Add a toolStripbutton for ToolStrip and set its Enabled=True, Checked=True
4. Enable high contrast mode
4. Run the app and launch Accessibility Insights for Windows tool

**Actual behavior:**
High contrast: Aquatic
![image](https://user-images.githubusercontent.com/62929087/145318964-e54e5b2e-cf7e-44dd-bcaa-caf1084fd844.png)

High contrast: Dusk
![image](https://user-images.githubusercontent.com/62929087/145318978-415dabee-2a01-49ca-84f3-a73b67198daa.png)

High contrast: Night sky
![image](https://user-images.githubusercontent.com/62929087/145318992-b3ad18b4-c65e-4757-a431-2a2d045b7aa3.png)

**Expected behavior:**
The color contrast ratio should greater than 3:1

**Comment by Tanya-Solyanik** [comment]
@Amy-Li03 @vladimir-krestov  - same question as in #6220  - had we fixed this in 4.8.1?

**Comment by Amy-Li03** [comment]
@Tanya-Solyanik verified this bug in 4.8.1 on win11 OS after installed latest .Net framework 4.8.1 msu: [\\cpvsbuild\drops\dev14\NetFXDev1\layouts\amd64ret\04349.00\enu\netfx\fullvnextmsu\msu](file://cpvsbuild/drops/dev14/NetFXDev1/layouts/amd64ret/04349.00/enu/netfx/fullvnextmsu/msu), bug is still reproducing, the test result is same as above screenshot in Actual behavior.

**Comment by dkazennov** [comment]
I believe the should probably close this issue for the same reasons I describe in https://github.com/dotnet/winforms/issues/6220

**Comment by merriemcgaw** [comment]
Agreed - as long as the text of the buttons is at the right contrast I think we don't need to change anything here right now.
