### ISSUE TITLE
Multiline Checkbox text is deleted on Save

### ISSUE THREAD

**Issue by paul1956** [dotnet/winforms#8735]
### Environment

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.6.0 Preview 1.0

### .NET version

N/A

### Did this work in a previous version of Visual Studio and/or previous .NET release?

Unknown

### Issue description

When multiline CheckBox is created, using Designer, when form is saved the text is deleted.

### Steps to reproduce

Create a form, add a CheckBox, Use dropdown under CheckBox.Text to enter multiple lines of text. Hit <Control><Enter> to Save the  text and you will see it on the design surface. Now Save the Form. The text is deleted from Form.Designer.
[CheckBoxText Disapears.zip](https://github.com/dotnet/winforms/files/10877409/CheckBoxText.Disapears.zip)

### Diagnostics

```text
Silent. No errors.
```

**Comment by elachlan** [comment]
@Olina-Zhang can your team please verify this issue?

**Comment by Olina-Zhang** [comment]
Tested this issue, it can reproduce after serialization in core designer, doesn't repro in Visual Studio 17.4.5. Will open a GH issue in Winforms designer repo.

**Comment by Olina-Zhang** [comment]
Filed a Winforms designer repo issue to track: https://github.com/microsoft/winforms-designer/issues/4980

**Comment by Olina-Zhang** [comment]
This issue was fixed in internal VS build, please use incoming Visual Studio 2022 preview build for testing.
![Text_Fixed](https://user-images.githubusercontent.com/26474449/224634698-10b370c9-6981-4123-96d2-461f0f57a7f8.gif)

**Comment by paul1956** [comment]
@Olina-Zhang it would help people outside the development team if when you close something as complete, we had some idea what public release it is targeted at. I don't need a guarantee just a "this will not be in before version X.Y" so we don't waste time trying every preview and finding the issue still there.

**Comment by Olina-Zhang** [comment]
@paul1956 the fixing of this issue now is also in public release: Visual Studio 17.5.3.
